with-previous-version: use last file in directory by default

diff --git a/with-previous-version b/with-previous-version
--- a/with-previous-version
+++ b/with-previous-version
@@ -5,8 +5,9 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 FILE_PATH_REL="$1"
 
 if [[ -z "$FILE_PATH_REL" ]]; then
-  echo "Error: no file path provided"
-  exit 1
+  # echo "Error: no file path provided"
+  # exit 1
+  FILE_PATH_REL=$(ls -1 | tail -n 1)
 fi
 
 PREVIOUS_FILE_VERSION_PATH_REL=$($SCRIPT_DIR/file-name-previous-version.sh "$FILE_PATH_REL")
